apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: {{ .Values.services.srv.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ .Values.services.srv.name }}
spec:
  runtime: {{ .Values.services.srv.runtime }}
<% if((hana && runtime === "nodejs16") || ((hana || authentication) && runtime === "python39")){ -%>
  runtimeImageOverride: {{ .Values.services.srv.runtimeImageOverride }}
<% } -%>
  scaleConfig:
    maxReplicas: 5
    minReplicas: 1
  resourceConfiguration:
    function:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
    build:
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 1
          memory: 1Gi
<% if(authentication || apiS4HC || hana || apiGraph || apiDest){ -%>
  env:
    - name: SERVICE_BINDING_ROOT
      value: /bindings
<% if(runtime === "nodejs16"){ -%>
    - name: DEBUG
      value: '<%= projectName %>-srv:*'
<% } -%>
  secretMounts:
<% if(authentication || apiS4HC || apiGraph || (apiDest && runtime !== "python39")){ -%>
    - secretName: {{ .Values.services.uaa.bindingSecretName }}
      mountPath: "/bindings/<%= projectName %>-uaa"
<% } -%>
<% if(apiS4HC || apiGraph || apiDest){ -%>
    - secretName: {{ .Values.services.dest.bindingSecretName }}
      mountPath: "/bindings/<%= projectName %>-dest"
<% } -%>
<% if(hana){ -%>
    - secretName: {{ .Values.services.hdi.bindingSecretName }}
      mountPath: "/bindings/<%= projectName %>-hdi"
<% } -%>
<% } -%>
  source:
<% if (source === "git"){ -%>
    gitRepository:
      url: <%= gitURL %>
      baseDir: <%= gitBaseDir %>
      reference: <%= gitReference %>
<% if(gitAuth !== "none"){ -%>
      auth:
        type: <%= gitAuth %>
        secretName: <%= projectName %>-git-creds
<% } -%>
<% }else{ -%>
    inline:
<% } -%>